### PR TITLE
Solved Issue #2: Is it possible to choose whether or not to skew the non-foreground cards?

### PR DESCRIPTION
**Pull request by yashas-hm**
Solved Issue #2 
Is it possible to choose whether or not to skew the non-foreground cards?

I have added a parameter which can be controlled by the user by passing values through the skewAngle parameter. By default it is 0.25.

### CODE REVIEW

**Comment by Ultranmus** [comment]
@yashas-hm i think it will be better if you remove the -ve from skew angle, this way developer can decide the direction -ve or +ve

**Comment by yashas-hm** [comment]
@delwar36 fixed

**Comment by Ultranmus** [comment]
@yashas-hm you forget to update the default skew angle to -ve in this.skewAngle=-0.25

**Comment by yashas-hm** [comment]
@delwar36 done

**Comment by yashas-hm** [comment]
The fix for issue #3 is not being reflected on pub dev.
Please check thanks

**Comment by yashas-hm** [comment]
Hi, please check the PR #5

**Pull request merged**
